### ISSUE TITLE
Fix Bactopia badge styling in example table 

### ISSUE THREAD

**Issue by cimendes** [microbinfie-hackathon2020/CSIS#55]
For uniformity purposes, TODO:

- [ ] Add the name of the tool to badge link to CI 
- [ ] Correct release to version and adjust colour
- [ ] Fix workflow link styling (should be bactopia.yml) 

<img width="650" alt="image" src="https://user-images.githubusercontent.com/15690332/158134826-ab17c5e9-ab32-4b35-9eb1-bfec02d6d12f.png">

CC @rpetit3

**Comment by rpetit3** [comment]
Hi @cimendes 

I've addressed each of these in https://github.com/microbinfie-hackathon2020/CSIS/pull/56. Although would you reconsider the stance on #3 (`bactopia.yml`)? 

I ask because Bactopia does a lot of testing that exceeds a single yaml file and the reason why I originally pointed to https://github.com/bactopia/bactopia/tree/master/.github/workflows.

Cheers,
Robert
